### PR TITLE
Should matter be the semantic field for the alloy brass?

### PR DESCRIPTION
**Pull request by severin31**
Again a question :-)

### CODE REVIEW

**Comment by barumau** [comment]
_Matter_ is a good semantic field for _brass_. All kinds of alloys and chemical compounds could go to that category, but not things that are made of them. So for example rock, granite, wood and air would go to the Nature category. Does that sound reasonable?

**Comment by severin31** [comment]
I need more knowledge.

https://en.m.wikipedia.org/wiki/Periodic_table
https://en.wikipedia.org/wiki/List_of_named_alloys
https://en.wikipedia.org/wiki/List_of_compounds

Chemical.Element.
Chemical.Alloy.
Chemical.Compounds.

Temptation...

I know that the goal of a semantic field is not to do science, but it would be easier for me, and it would be generous to promote. But harder to code, especially if we generalize this principle in biology 😱

I have to think. But if matter is only alloy, it's not a good idea to put it in matter. Why not a little category of just?

Alloy.

Does it matter? (Sorry, I had to do this joke)

**Comment by barumau** [comment]
It is hard to draw lines between chemistry, physics, materials science (incl. metallurgy) and even geology (ores and minerals!).

What we need is a system of categorization that is mostly intuitive and not too detailed. You should be able to categorize things based on what you have learned in school by the age of 15–16. It is too complex if categorizing words requires specialized university degrees.

**Review by barumau — APPROVED** [review]
Let's go forward! So I approve this and then change the category to _Material_.

When we have categorized all words, we can still look again at the results and make last adjustments. Let's keep in mind that what we need is a usable and informative categorization of meanings. It doesn't have to be perfect.

**Comment by severin31** [comment]
It will be perfect for now. Let's go on.

**Pull request merged**
